version: "3.7"
services:
  bento-tensorflow:
    image: bento-tf-gpu:latest
    build:
      context: deploy/tf_svc
      dockerfile: Dockerfile
    ports:
      - "6000:5000"
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
  bento-pytorch:
    image: bento-torch-gpu:latest
    build:
      context: deploy/pytorch_service
      dockerfile: Dockerfile
    ports:
      - "7000:5000"
    devices:
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools