version: 0.12.1
kind: BentoService
metadata:
  created_at: 2021-05-20 18:46:35.955838
  service_name: PytorchService
  service_version: 20210521014633_FC84DC
  module_name: bento_service_torch
  module_file: bento_service_torch.py
env:
  pip_packages:
  - bentoml==0.12.1
  - spacy==3.0.6
  - torchtext==0.9.1
  - torch==1.8.1
  conda_env:
    name: bentoml-default-conda-env
    dependencies: []
  python_version: 3.8.5
  docker_base_image: bentoml/model-server:0.12.1-py38
apis:
- name: predict
  docs: "BentoService inference API 'predict', input: 'JsonInput', output: 'JsonOutput'"
  input_type: JsonInput
  output_type: JsonOutput
  mb_max_batch_size: 4000
  mb_max_latency: 20000
  batch: false
  route: predict
  output_config:
    cors: '*'
artifacts:
- name: model
  artifact_type: PytorchModelArtifact
  metadata: {}
- name: tokenizer
  artifact_type: PickleArtifact
  metadata: {}
