---
### Tensorflow Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: tf-svc
  name: tf-svc
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tf-svc
  template:
    metadata:
      labels:
        app: tf-svc
    spec:
      containers:
        - name: bento-container
          image: aarnphm/bento-tf-gpu:latest
          imagePullPolicy: Always
          name: tf-svc
          resources:
            limits:
              nvidia.com/gpu: 1
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
### Tensorflow Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: tf-svc
  name: tf-svc
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: predict
      nodePort: 32610
      port: 60061
      protocol: TCP
      targetPort: 5000
  selector:
    app: tf-svc
  sessionAffinity: None
  type: LoadBalancer