version: 0.12.1
kind: BentoService
metadata:
  created_at: 2021-05-20 15:47:44.121395
  service_name: TensorflowService
  service_version: '20210520224742_038837'
  module_name: bento_service_tf
  module_file: bento_service_tf.py
env:
  pip_packages:
  - bentoml==0.12.1
  - tensorflow-gpu==2.4.0
  - tensorflow
  - pandas==1.2.2
  - scikit-learn==0.24.1
  conda_env:
    name: bentoml-default-conda-env
    dependencies: []
  python_version: 3.8.5
  docker_base_image: bentoml/model-server:0.12.1-py38
apis:
- name: predict
  docs: "BentoService inference API 'predict', input: 'JsonInput', output: 'DefaultOutput'"
  input_type: JsonInput
  output_type: DefaultOutput
  mb_max_batch_size: 4000
  mb_max_latency: 20000
  batch: false
  route: predict
  output_config:
    cors: '*'
artifacts:
- name: model
  artifact_type: KerasModelArtifact
  metadata: {}
- name: tokenizer
  artifact_type: PickleArtifact
  metadata: {}
